.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. airdollars_qt test_airdollars_qt
clean: FORCE
	$(MAKE) -C .. airdollars_qt_clean test_airdollars_qt_clean
check: FORCE
	$(MAKE) -C .. test_airdollars_qt_check
airdollars-qt airdollars-qt.exe: FORCE
	 $(MAKE) -C .. airdollars_qt
