#!/bin/bash

# This is a thin wrapper around airdollars-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using airdollars-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_AIRDOLLARSD

# Grab the value of $REAL_AIRDOLLARSCLI which may be airdollars-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_AIRDOLLARSCLI}" "$@" | sed 's/\r//'
